# Generated by Django 3.2 on 2021-04-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0002_auto_20210416_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ratingCount',
            new_name='ratingsCount',
        ),
    ]
