# Generated by Django 3.2 on 2021-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_db', '0003_rename_ratingcount_books_ratingscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(default='Untitled', max_length=250),
        ),
    ]
